validate-yaml: false
project:
  type: book
  preview: 
    host: 0.0.0.0
    port: 5000

book:
  title: "Journals"
  author: "James Eapen"
  listing: default
  repo-url: https://github.com/jamespeapen/journals/
  repo-actions: [source]
  sidebar: 
    collapse-level: 1
    style: "floating"
  # chapter list
  chapters:
    - contents.qmd
    - part: "Bioinformatics"
      chapters:
      - part: "Databases"
        chapters: 
          - src/bioinformatics/databases/evaluation_of_relational_and_nosql_database_architectures_to_manage_genomic_annotations.md
    - part: "Epigenetics"
      chapters: 
      - part: "General"
        chapters:
          - src/epigenetics/interplay_between_cancer_genome_epigenome.md
          - src/epigenetics/diverse_roles_dna_methylation_mammalian_development_disease.md
          - src/epigenetics/dna_methylation_loss_late_replicating_domains_linked_mitotic_cell_division.md
          - src/epigenetics/cell_division_drives_dna_methylation_loss_late_replicating_domains.md
    - part: "Cell-type vs cell-state"
      chapters:
        - src/cell_type_state/transition_states_and_cell_fate_decisions_in_epigenetic_landscapes.md
        - src/cell_type_state/defining_cell_type_states_single_cell_genomics.md
        - src/cell_type_state/the_evolving_concept_of_cell_identity_in_single_cell_era.md
        - src/cell_type_state/what_is_a_cell_type_how_to_define_it.md
        - src/cell_type_state/epigenetic_regulation_cell_fate_reprogramming.md
        - src/cell_type_state/control_of_cell_state_transitions.md
        - part: "RNA velocity"
          chapters:
            - src/cell_type_state/rna_velocity/rna_velocity_single_cells.md
            - src/cell_type_state/rna_velocity/generalizing_rna_velocity_to_transient_cell_states.md
            - src/cell_type_state/rna_velocity/rna_velocity_current_challenges_future_perspectives.md
            - src/cell_type_state/rna_velocity/multiomic_single_cell_velocity.md
        - part: "Lineage tracing"
          chapters: 
            - src/cell_type_state/lineage_tracing/lineage_tracing_human_tissues.md
        - part: "Cancer"
          chapters:
            - src/cell_type_state/cancer/integrative_model_of_cellular_states_plasticity_genetics_glioblastoma.md
        - part: "State space"
          chapters: 
            - src/cell_type_state/state_space/dreiss_using_state_space_model_infer_gene_exp_dynamics.md
    - part: "Transcriptomics"
      chapters:
      - part: "Single-nucleus RNA-seq"
        chapters:
          - src/transcriptomics/snRNA/Systematic_comparison_of_scRNA_and_snRNA-sequencing_methods.md
          - src/transcriptomics/snRNA/snRNA_eq_Is_Not_Suitable_for_Detection_of_Microglial_Activation_Genes_in_Humans.md
    - part: "Cancer"
      chapters:
        - src/cancer/non_genetic_determinants_malignant_clonal_fitness_sc_resolution.md 
        - part: "Ovarian cancer"
          chapters: 
            - src/cancer/ovarian_cancer/clear_cell_endometrioid_carcinomas_differences_attributable_to_distinct_cells_of_origin.md
            - src/cancer/ovarian_cancer/single_cell_landscape_hgsoc.md
            - src/cancer/ovarian_cancer/stem_like_epithelial_cells_concentrated_in_distal_end.md
    - part: "Ageing"
      chapters: 
        - src/ageing/counteracting_age_related_VEGF_insufficiecy.md
    - part: "Cellular Senescence"
      chapters:
        - src/senescence/Senescence-Associated_Secretory_Phenotypes.md
        - src/senescence/Four_faces_of_cellular_senescence.md
        - src/senescence/inhibition_of_SIPS_in_PSEN1_mutated_cells_with_water_soluble_coenzyme_q10.md
        - src/senescence/epigenetic_basis_of_senescence_implications_in_aging.md
        - src/senescence/Cellular_senescence_Immunosurveillance_and_future_immunotherapy.md
        - src/senescence/transcriptome_signature_of_cellular_senescence.md
        - src/senescence/Cellular_senescence_Defining_a_path_forward.md
        - src/senescence/impaired_immune_surveillance_accelerates_accumulation_of_senescent_cells_and_aging.md
        - src/senescence/Astrocyte_senescence_promotes_glutamate_toxicity_in_cortical_neurons.md
        - src/senescence/multidim_systems_bio_analysis_senescence_aging_disease.md
        - src/senescence/Single-Cell_Transcriptome_Analysis_Reveals_Six_Subpopulations.md
        - src/senescence/Cellular_senescence_and_failure_of_myelin_repair_in_MS.md
        - src/senescence/lncRNA_MIR31HG_regulates_the_senescence_associated_secretory_phenotype.md
        - src/senescence/early_onset_senescence_cognitive_impairment_in_murine_model_of_repeated_mTBI.md
        - src/senescence/aged_immune_system_drives_senescence_ageing_of_solid_organs.md
    - part: "Neuroscience"
      chapters:
      - part: "Neurodegeneration"
        chapters:
          - src/neuroscience/neurodegeneration/ad/Cellular_Senescence_in_Neurodegenerative_Diseases.md
          - src/neuroscience/neurodegeneration/ad/Aging_as_a_risk_factor_for_neurodegenerative_disease.md
          - src/neuroscience/neurodegeneration/genetically_determined_susceptibility_neurodegeneration_expression_inflammatory_genes.md
          - src/neuroscience/neurodegeneration/evidence_of_the_cellular_senescence_stress_response_in_mitotically_active_brain_cell_cancer_neurodegeneration.md
          - src/neuroscience/neurodegeneration/neuroblast_senescence_aged_brain_augments_nk_cell_cytotoxicity_leading_to_impaired_neurogenesis_cognition.md
          - src/neuroscience/neurodegeneration/dystrophic_microglia_associated_with_neurodegenerative_disease_not_healthy_ageing_in_brain.md
          - part: "Alzheimer’s Disease"
            chapters: 
              - src/neuroscience/neurodegeneration/ad/inflammation_a_beta_deposition_nft_tangle_formation_correlates_of_ad_neurodegeneration.md
              - src/neuroscience/neurodegeneration/ad/The_Genetic_Landscape_of_AD.md
              - src/neuroscience/neurodegeneration/ad/Genetics_of_AD.md
              - src/neuroscience/neurodegeneration/ad/When_does_AD_really_start.md
              - src/neuroscience/neurodegeneration/ad/Genetic_meta-analysis_of_diagnosed_AD.md
              - src/neuroscience/neurodegeneration/ad/The_Cellular_Phase_of_AD.md
              - src/neuroscience/neurodegeneration/ad/Single-cell_transcriptomic_analysis_of_AD.md
              - src/neuroscience/neurodegeneration/ad/AD_Patient_Microglia_Exhibit_Enhanced_Aging_and_Unique_Transcriptional_Activation.md
              - src/neuroscience/neurodegeneration/ad/Dysregulation_of_the_epigenetic_landscape_of_normal_aging_in_AD.md
              - src/neuroscience/neurodegeneration/ad/Loss-of-function_of_p53_isoform_accelerates_brain_aging_in_zebrafish.md
              - src/neuroscience/neurodegeneration/ad/Telomere_Attrition_in_Neurodegenerative_Disorders.md
              - src/neuroscience/neurodegeneration/ad/Cerebrovascular_Senescence_Is_Associated_With_Tau_Pathology_in_AD.md
              - src/neuroscience/neurodegeneration/ad/molecular_mechanism_for_age_related_memory_loss_rbap48.md
              - src/neuroscience/neurodegeneration/ad/big_data_analysis_of_genes_associated_with_neuropsychiatric_disorders_in_an_AD_animal_model.md
              - part: "Cellular senescence and AD"
                chapters:
                  - src/neuroscience/neurodegeneration/ad/Vascular_Cell_Senescence_Contributes_to_Blood–Brain_Barrier_Breakdown.md
                  - src/neuroscience/neurodegeneration/ad/cellular_senescence_iron_dyshomeostasis_in_AD.md
                  - src/neuroscience/neurodegeneration/ad/Cellular_senescence_and_AD.md
                  - src/neuroscience/neurodegeneration/ad/Senescence_as_an_Amyloid_Cascade.md
                  - src/neuroscience/neurodegeneration/ad/Astrocyte_Senescence_and_AD.md
    - index.qmd
bibliography: references.bib

format:
  html:
    theme: 
      light: lumen
      dark: superhero
  pdf:
    documentclass: article

