# Contents {.unnumbered}

### Bioinformatics

- [MATCHER: manifold alignment reveals correspondence between single cell
  transcriptome and epigenome dynamics](src/bioinformatics/matcher_manifold_alignment_correspondence_sc_rna_epi.md)

#### Databases

- [Evaluation of relational and NoSQL database architectures to manage genomic
  annotations](src/bioinformatics/databases/evaluation_of_relational_and_nosql_database_architectures_to_manage_genomic_annotations.md)

### Epigenetics

- [Interplay between the cancer genome and
  epigenome](src/epigenetics/interplay_between_cancer_genome_epigenome.md)

- [An Overview of Genome Organization and How We Got There: from FISH to Hi-C](src/epigenetics/overview_genome_org_how_we_got_there_fish_hic.md)

- [The diverse roles of DNA methylation in mammalian development and
  disease](./src/epigenetics/diverse_roles_dna_methylation_mammalian_development_disease.md)

- [DNA methylation loss in late-replicating domains is linked to mitotic cell division](src/epigenetics/dna_methylation_loss_late_replicating_domains_linked_mitotic_cell_division.md)
- [Cell division drives DNA methylation loss in late-replicating domains in primary human cells](src/epigenetics/cell_division_drives_dna_methylation_loss_late_replicating_domains.md)

#### Chromatin organization

- [RNA promotes the formation of spatial compartments in the nucleus](src/epigenetics/rna_promotes_formation_spatial_compartments_in_nucleus.md)

### Cell type vs cell state

- [Quantifying cell-state densities in single-cell phenotypic landscapes using
Mellon](src/cell_type_state/quantifying_cell_state_densities_mellon.md)

- [Precise identification of cell states altered in disease using healthy single-cell
  references](src/cell_type_state/precise_identification_cell_states_altered_in_disease_using_healthy_sc_references.md)

- [SEACells infers transcriptional and epigenomic cellular states from single-cell genomics data](src/cell_type_state/seacells_infers_transcriptional_epigenomic_states.md)

- [Transition states and cell fate decisions in epigenetic landscapes
](src/cell_type_state/transition_states_and_cell_fate_decisions_in_epigenetic_landscapes.md)

- [Defining cell types and states with single-cell
  genomics](src/cell_type_state/defining_cell_type_states_single_cell_genomics.md)

- [The evolving concept of cell identity in the single cell era
  ](src/cell_type_state/the_evolving_concept_of_cell_identity_in_single_cell_era.md)

- [What is a cell type and how to define it](src/cell_type_state/what_is_a_cell_type_how_to_define_it.md)

- [Epigenetic regulation of cell fate reprogramming in aging and disease: A predictive computational
  model](src/cell_type_state/epigenetic_regulation_cell_fate_reprogramming.md)

- [Control of cell state transitions](src/cell_type_state/control_of_cell_state_transitions.md)

- [Cell Fate Decision as High-Dimensional Critical State Transition](src/cell_type_state/cell_fate_transition_high_dim_critical_state_transition.md)

- [Dynamic Heterogeneity and DNA Methylation in Embryonic Stem Cells](src/cell_type_state/dynamic_heterogeneity_dna_meth_escs.md)

- [Transcriptome-wide noise controls lineage choice in mammalian progenitor cells](src/cell_type_state/transcriptome_wide_noise_controls_lineage_choice.md)

#### RNA velocity

- [RNA velocity of single cells](src/cell_type_state/rna_velocity/rna_velocity_single_cells.md)

- [Generalizing RNA velocity to transient cell states through dynamical
  modeling](src/cell_type_state/rna_velocity/generalizing_rna_velocity_to_transient_cell_states.md)
  
- [RNA velocity—current challenges and future
  perspectives](src/cell_type_state/rna_velocity/rna_velocity_current_challenges_future_perspectives.md)

- [Multi-omic single-cell velocity models epigenome–transcriptome interactions
  and improves cell fate prediction](src/cell_type_state/rna_velocity/multiomic_single_cell_velocity.md)

#### Lineage tracing

- [Defining ancestry, heritability and plasticity of cellular phenotypes in somatic
  evolution](src/cell_type_state/lineage_tracing/defining_ancestry_heritability_plasticity_cell_phenotypes_evolution.md)

- [Lineage tracing in human tissues](src/cell_type_state/lineage_tracing/lineage_tracing_human_tissues.md)

- [Barcode-free prediction of cell lineages from scRNA-seq datasets](src/cell_type_state/lineage_tracing/gemli_barcode_free_lineage_prediction.md)

#### Cancer

- [An Integrative Model of Cellular States, Plasticity, and Genetics for
  Glioblastoma](src/cell_type_state/cancer/integrative_model_of_cellular_states_plasticity_genetics_glioblastoma.md)

#### Fallopian tube

- [The Notch and Wnt pathways regulate stemness and differentiation in human
  fallopian tube organoids](src/cell_type_state/fte/notch_wnt_regulate_stemness_differentiation_fte.md)

#### State space

- [DREISS: Using State-Space Models to Infer the Dynamics of Gene Expression
Driven by External and Internal Regulatory
Networks](src/cell_type_state/state_space/dreiss_using_state_space_model_infer_gene_exp_dynamics.md)

### Transcriptomics

- [The triumphs and limitations of computational methods for
  scRNA-seq](src/transcriptomics/scRNA/triumphs_limitations_computational_methods_scRNAseq.md)

- [Separating measurement and expression models clarifies confusion in single-cell RNA sequencing analysis](src/transcriptomics/scRNA/separating_measurement_expression_models_clarifies_confusion_scRNAseq_analysis.md)

##### Single-nucleus RNA-seq

- [Systematic comparison of single-cell and single-nucleus RNA-sequencing
  methods](src/transcriptomics/snRNA/Systematic_comparison_of_scRNA_and_snRNA-sequencing_methods.md)

- [Single-Nucleus RNA-Seq Is Not Suitable for Detection of Microglial Activation
  Genes in Humans](src/transcriptomics/snRNA/snRNA_eq_Is_Not_Suitable_for_Detection_of_Microglial_Activation_Genes_in_Humans.md)

### Cancer

- [Selective advantage of epigenetically disrupted cancer cells via phenotypic inertia](src/cancer/selective_advantage_cancer_cells_phenotypic_inertia.md)

- [Non-genetic determinants of malignant clonal fitness at single-cell resolution](src/cancer/non_genetic_determinants_malignant_clonal_fitness_sc_resolution.md)

##### Cancer stem cells

- [Heterogeneity in Cancer: Cancer Stem Cells versus Clonal
  Evolution](src/cancer/csc/csc_vs_clonal_evolution.md)

#### Ovarian cancer

- [Cellular heterogeneity of human fallopian tubes in normal and hydrosalpinx
  disease states identified using scRNA-seq](src/cancer/ovarian_cancer/cellular_heterogeneity_ft_scRNA_seq.md)

- [A single-cell landscape of high-grade serous ovarian
  cancer](src/cancer/ovarian_cancer/single_cell_landscape_hgsoc.md)

- [The Repertoire of Serous Ovarian Cancer Nongenetic Heterogeneity Revealed by Single-Cell Sequencing of Normal Fallopian Tube Epithelial Cells](src/cancer/ovarian_cancer/repertoire_of_hgsoc_non_genetic_heterogeneity_fte.md)

- [Identifying an ovarian cancer cell hierarchy regulated by bone morphogenetic
  protein 2](src/cancer/ovarian_cancer/identifying_ovca_cell_hierarchy_regulated_by_bmp2.md)

- [Clear cell and endometrioid carcinomas: are their differences
attributable to distinct cells of origin?](src/cancer/ovarian_cancer/clear_cell_endometrioid_carcinomas_differences_attributable_to_distinct_cells_of_origin.md)

- [Both fallopian tube and ovarian surface epithelium are cells-of-origin for
  high-grade serous ovarian carcinoma](src/cancer/ovarian_cancer/both_fte_ose_are_cells_of_origin_for_hgsoc.md)

- [Stem-Like Epithelial Cells Are Concentrated in the Distal End of the
  Fallopian Tube: A Site for Injury and Serous Cancer Initiation](src/cancer/ovarian_cancer/stem_like_epithelial_cells_concentrated_in_distal_end.md)

- [Developing ovarian cancer stem cell models: laying the pipeline from
  discovery to clinical intervention](src/cancer/ovarian_cancer/developing_ovarian_cancer_stem_cell_models.md)

### Ageing

- [Counteracting age-related VEGF signaling insufficiency promotes healthy aging and extends life span
](src/ageing/counteracting_age_related_VEGF_insufficiecy.md)

### Cellular Senescence

- [Senescence-Associated Secretory Phenotypes Reveal Cell-Nonautonomous
  Functions of Oncogenic RAS and the p53 Tumor Suppressor](src/senescence/Senescence-Associated_Secretory_Phenotypes.md)

- [Four faces of cellular senescence](src/senescence/Four_faces_of_cellular_senescence.md)

- [Inhibition of stress induced premature senescence in presenilin-1 mutated
  cells with water soluble Coenzyme Q<sub>10</sub>](src/senescence/inhibition_of_SIPS_in_PSEN1_mutated_cells_with_water_soluble_coenzyme_q10.md)

- [Epigenetic Basis of Cellular Senescence and Its Implications in Aging](src/senescence/epigenetic_basis_of_senescence_implications_in_aging.md)

- [Cellular senescence: Immunosurveillance and future immunotherapy](src/senescence/Cellular_senescence_Immunosurveillance_and_future_immunotherapy.md)

- [Transcriptome signature of cellular senescence](src/senescence/transcriptome_signature_of_cellular_senescence.md)

- [Cellular senescence: Defining a path forward](src/senescence/Cellular_senescence_Defining_a_path_forward.md)

- [Impaired immune surveillance accelerates accumulation of senescent cells and
  aging ](src/senescence/impaired_immune_surveillance_accelerates_accumulation_of_senescent_cells_and_aging.md)

- [Astrocyte senescence promotes glutamate toxicity in cortical neurons](src/senescence/Astrocyte_senescence_promotes_glutamate_toxicity_in_cortical_neurons.md)

- [A multidimensional systems biology analysis of cellular senescence in aging
  and disease](src/senescence/multidim_systems_bio_analysis_senescence_aging_disease.md)

- [Single-Cell Transcriptome Analysis Reveals Six Subpopulations Reflecting
  Distinct Cellular Fates in Senescent Mouse Embryonic Fibroblasts](src/senescence/Single-Cell_Transcriptome_Analysis_Reveals_Six_Subpopulations.md)

- [Cellular senescence and failure of myelin repair in MS](src/senescence/Cellular_senescence_and_failure_of_myelin_repair_in_MS.md)

- [Early onset senescence and cognitive impairment in a murine model of repeated
  mTBI](src/senescence/early_onset_senescence_cognitive_impairment_in_murine_model_of_repeated_mTBI.md)

- [An aged immune system drives senescence and ageing of solid organs](src/senescence/aged_immune_system_drives_senescence_ageing_of_solid_organs.md)

- [The long non-coding RNA *MIR31HG* regulates the senescence associated
  secretory phenotype](src/senescence/lncRNA_MIR31HG_regulates_the_senescence_associated_secretory_phenotype.md)

### Neuroscience

#### Neurodegeneration

- [Cellular Senescence in Neurodegenerative Diseases](src/neuroscience/neurodegeneration/ad/Cellular_Senescence_in_Neurodegenerative_Diseases.md)

- [Aging as a risk factor for neurodegenerative disease](src/neuroscience/neurodegeneration/ad/Aging_as_a_risk_factor_for_neurodegenerative_disease.md)

- [Genetically determined susceptibility to neurodegeneration is associated with
  expression of inflammatory genes](src/neuroscience/neurodegeneration/genetically_determined_susceptibility_neurodegeneration_expression_inflammatory_genes.md)

- [Evidence of the Cellular Senescence Stress Response in Mitotically Active
  Brain Cells-Implications for Cancer and Neurodegeneration](src/neuroscience/neurodegeneration/evidence_of_the_cellular_senescence_stress_response_in_mitotically_active_brain_cell_cancer_neurodegeneration.md)

- [Neuroblast senescence in the aged brain augments natural killer cell cytotoxicity leading to impaired neurogenesis and cognition
  ](src/neuroscience/neurodegeneration/neuroblast_senescence_aged_brain_augments_nk_cell_cytotoxicity_leading_to_impaired_neurogenesis_cognition.md)

- [Dystrophic microglia are associated with neurodegenerative disease and not
  healthy aging in the human brain](src/neuroscience/neurodegeneration/dystrophic_microglia_associated_with_neurodegenerative_disease_not_healthy_ageing_in_brain.md)

##### Alzheimer’s Disease

- [Inflammation, A beta deposition, and neurofibrillary tangle formation as
  correlates of Alzheimer's disease neurodegeneration](src/neuroscience/neurodegeneration/ad/inflammation_a_beta_deposition_nft_tangle_formation_correlates_of_ad_neurodegeneration.md)

- [The Genetic Landscape of Alzheimer’s Disease](src/neuroscience/neurodegeneration/ad/The_Genetic_Landscape_of_AD.md)

- [Genetics of Alzheimer’s disease: where we are, and where we are going](src/neuroscience/neurodegeneration/ad/Genetics_of_AD.md)

- [When does Alzheimer’s disease really start? The Role of Biomarkers](src/neuroscience/neurodegeneration/ad/When_does_AD_really_start.md)

- [Genetic meta-analysis of diagnosed Alzheimer’s disease](src/neuroscience/neurodegeneration/ad/Genetic_meta-analysis_of_diagnosed_AD.md)

- [The Cellular Phase of Alzheimers Disease](src/neuroscience/neurodegeneration/ad/The_Cellular_Phase_of_AD.md)

- [Single-cell transcriptomic analysis of Alzheimer’s disease](src/neuroscience/neurodegeneration/ad/Single-cell_transcriptomic_analysis_of_AD.md)

- [Alzheimer’s Patient Microglia Exhibit Enhanced Aging and Unique
  Transcriptional Activation](src/neuroscience/neurodegeneration/ad/AD_Patient_Microglia_Exhibit_Enhanced_Aging_and_Unique_Transcriptional_Activation.md)

- [Dysregulation of the epigenetic landscape of normal aging in Alzheimer’s
  disease](src/neuroscience/neurodegeneration/ad/Dysregulation_of_the_epigenetic_landscape_of_normal_aging_in_AD.md)

- [Loss-of-function of p53 isoform Δ113p53 accelerates brain aging in
  zebrafish](src/neuroscience/neurodegeneration/ad/Loss-of-function_of_p53_isoform_accelerates_brain_aging_in_zebrafish.md)

- [Telomere Attrition in Neurodegenerative Disorders](src/neuroscience/neurodegeneration/ad/Telomere_Attrition_in_Neurodegenerative_Disorders.md)

- [Cerebrovascular Senescence Is Associated With Tau Pathology in Alzheimer's
  Disease](src/neuroscience/neurodegeneration/ad/Cerebrovascular_Senescence_Is_Associated_With_Tau_Pathology_in_AD.md)

- [Molecular Mechanism for Age-Related Memory Loss: The Histone-Binding Protein
  RbAp48](src/neuroscience/neurodegeneration/ad/molecular_mechanism_for_age_related_memory_loss_rbap48.md)

- [Big Data Analysis of Genes Associated With Neuropsychiatric Disorders in an
  Alzheimer’s Disease Animal Model](src/neuroscience/neurodegeneration/ad/big_data_analysis_of_genes_associated_with_neuropsychiatric_disorders_in_an_AD_animal_model.md)

###### Cellular senescence and AD

- [Vascular Cell Senescence Contributes to Blood–Brain Barrier Breakdown](src/neuroscience/neurodegeneration/ad/Vascular_Cell_Senescence_Contributes_to_Blood%E2%80%93Brain_Barrier_Breakdown.md)

- [Cellular Senescence and Iron Dyshomeostasis in Alzheimer’s Disease](src/neuroscience/neurodegeneration/ad/cellular_senescence_iron_dyshomeostasis_in_AD.md)

- [Cellular senescence and Alzheimer disease: the egg and the chicken
  scenario](src/neuroscience/neurodegeneration/ad/Cellular_senescence_and_AD.md)

- [Senescence as an Amyloid Cascade: The Amyloid Senescence Hypothesis](src/neuroscience/neurodegeneration/ad/Senescence_as_an_Amyloid_Cascade.md)

- [Astrocyte Senescence and Alzheimer’s Disease: A Review](src/neuroscience/neurodegeneration/ad/Astrocyte_Senescence_and_AD.md)

